### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by galary** [lichenbuliren/vuex-notes-app#5]
localhost/:9 GET http://localhost:8088/stylesheets/stylesheet.css 
index.js?2c45:31 [HMR] Vue component hot reload shim applied.
vue.common.js?e881:1137 [Vue warn]: Cannot find element: #app

**Comment by lichenbuliren** [comment]
写了篇新的，可以参考这新篇来运行：https://segmentfault.com/a/1190000011099751
